export default ind;
declare namespace ind {
    const titleTime: string;
    const Greetings: string[];
    function reportErrorFound(usedPrefix: any, command: any): any;
    function reportShort(): string;
    function reportLong(): string;
    function From(): string;
    function Message(): string;
    function reportMessage(command: any): any;
    function PanelMenu(prefix: any, pushname: any, actividad: any, role: any, monospace: any, nwn: any): string;
    function FooterPM(CovidApi: any): string;
    function PanelMenu2(prefix: any, monospace: any): string;
    function MenuArte(prefix: any, monospace: any): string;
    function AniMenu(prefix: any, monospace: any): string;
    function MenuH(prefix: any, monospace: any): string;
    function BanCall(helpcall: any): string;
    function AutoSaludo(): string;
    function Wlc1(): string;
    function Wlc2(): string;
    function Wlc3(num: any, metadata: any, dateComplete: any, gpdesc: any): string;
    function Wlc4(): string;
    function Wlc5(num: any): string;
    function NoSpam1(): string;
    function NoSpam2(pushname: any): string;
    function NoReg(pushname: any): string;
    function PreFijo(): string;
    function Erreply(): string;
    function SinLimite(pushname: any): string;
    function Limite(pushname: any): string;
    function NivelUp(dateComplete: any, senderNumber: any, getLevel: any, getLevelingLevel: any, sender: any, per: any, getLevelingXp: any, role: any, role2: any): string;
    function MinGp1(): string;
    function MinGp2(): string;
    function NoTraba1(): string;
    function NoTraba2(saltos: any, eliminar: any, pushname: any): string;
    function NoPriv(privcre: any): string;
    function NoLinks1(): string;
    function NoLinks2(): string;
    function NoLinks3(): string;
    function Pong(conexiont: any): string;
    function NoReg2(prefix: any): string;
    function SoloGp(): string;
    function SoloAdm(): string;
    function YaActivo(command: any): string;
    function YaActivoSi(command: any, groupName: any): string;
    function YaActivoNo(command: any, groupName: any): string;
    function ActiVar(): string;
    function DesActiVar(): string;
    function AdminBot(): string;
    function SoloCreador(): string;
    function Modo0(): string;
    function Modo1(): string;
    function Modo2(): string;
    function Modo3(): string;
    function Modo4(): string;
    function ModNet0(): string;
    function ModNet1(): string;
    function ModNet2(): string;
    function ModNet3(): string;
    function ModNet4(): string;
    function NoPriv1(): string;
    function NoPriv2(): string;
    function PreDit0(): string;
    function PreDit1(): string;
    function PreDit2(): string;
    function NomBot0(): string;
    function NomBot1(): string;
    function NomBot2(): string;
    function PrinCre0(): string;
    function PrinCre1(): string;
    function PrinCre2(): string;
    function MyRed0(): string;
    function MyRed1(): string;
    function MyRed2(): string;
    function UsLimit0(): string;
    function UsLimit1(): string;
    function UsLimit2(): string;
    function UsLimit3(): string;
    function UsLimit4(): string;
    function PfBot0(): string;
    function PfBot1(): string;
    function ProCes(pushname: any): string;
    function QuImage(prefix: any, command: any): string;
    function SuPrim(): string;
    function NoTexto(): string;
    function BcGrupos0(gmap: any): string;
    function BcGrupos1(gmap: any): string;
    function BcTodos0(tmap: any): string;
    function BcTodos1(): string;
    function BanUser0(): string;
    function BanUser1(): string;
    function CerrarGp0(pushname: any, prefix: any, command: any): string;
    function CerrarGp1(UwU: any, pushname: any): string;
    function CerrarGp2(): string;
    function AbrirGp(): string;
    function NomGp0(): string;
    function NomGp1(groupName: any): string;
    function DesGp0(): string;
    function DesGp1(nwn: any, groupDesc: any): string;
    function PfGp0(): string;
    function PfGp1(): string;
    function ToDos(groupName: any, pushname: any, texto: any): string;
    function DarP(usuariop: any, pushname: any): string;
    function QuitP(usuarioq: any, pushname: any): string;
    function BanSer(adiuser: any, pushname: any): string;
    function UsEnLinea(): string;
    function Baneao(senderNumber: any): string;
    function BotInfo(): string;
    function GraciAs(): string;
    function MasCmds(): string;
    function YaReg(): string;
    function MyReg0(): string;
    function MyReg1(): string;
    function MyReg2(): string;
    function MyReg3(): string;
    function MyReg4(): string;
    function MyReg5(nwn: any, time: any, nomreg: any, pushname: any, edreg: any, sender: any, codereg: any): string;
    function MyReg6(): string;
    function CmdsR0(): string;
    function CmdsR1(): string;
    function CmdsA0(): string;
    function CmdsA1(): string;
    function CmdsO0(): string;
    function CmdsO1(): string;
    function CmdsH0(): string;
    function CmdsH1(): string;
    function MCmds0(): string;
    function MCmds1(): string;
    function OffLineInfo(): string;
    function BotIdiomChanged(lang: any): void;
}
//# sourceMappingURL=ind.d.ts.map